name: Everyday Lotto2

env:
  DH_LOTTERY_USER_ID: ${{ secrets.DH_LOTTERY_USER_ID2 }}
  DH_LOTTERY_PASSWORD: ${{ secrets.DH_LOTTERY_PASSWORD2 }}
  AMOUNT_PER_DAY: ${{ vars.AMOUNT_PER_DAY }}
  SLACK_BOT_TOKEN: ${{ vars.SLACK_BOT_TOKEN }}
  SLACK_CHANNEL_ID: ${{ vars.SLACK_CHANNEL_ID }}

on:
  schedule:
    - cron: '55 1 * * 1-5'

jobs:
  lotto:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run job
